Disable logging_collector feature
- Causes all log messages to be written to stderr
- Fixes failing test_basic on Fedora:

line 32, in test_basic
    self.assertRegexpMatches(pgsql.read_log(), 'is ready to accept
    connections')
    AssertionError: Regexp didn't match: 'is ready to accept
    connections' not found in 'LOG:  redirecting log output to logging
    collector process\nHINT:  Future log output will appear in directory
    "pg_log".\n'